### ISSUE TITLE
[VSC] kailua.json의 start_path를 정상적으로 열지 못합니다.

### ISSUE THREAD

**Issue by JamesKim2998** [devcat-studio/kailua#2]
안녕하세요.

kailua.json을 설정시 아래와 같은 오류가 발생합니다.
``
Couldn't open a start path. (Cause: Access is denied. (os error 5))
``

관리자 권한으로 VSC를 실행해도 동일한 오류가 발생합니다.
또한 절대 경로로 실행해도 마찬가지입니다.

아래는 제 kailua.json 파일입니다.
```json
// 상대경로 버전
{
    "start_path": "Assets",
}
```
```json
// 절대경로 버전
{
    "start_path": "C:\\Users\\James Kim\\Develop\\Project\\SomeProject\\Assets",
}
```

위의 문제와 별개로 Unity에서 kailua를 적용해서 사용해볼까 생각 중입니다.
구체적으로는 tencent의 xLua를 이용해서 바인딩을 하고,
kailua를 통해 static type checking을 해볼까 합니다.

**Comment by lifthrasiir** [comment]
@JamesKim2998 안녕하세요. `start_path`는 디렉토리가 아니라 체킹을 시작할 **루아 파일**의 경로를 넣는 설정입니다. (`.vscode` 디렉토리가 있는 디렉토리에 상대적인 경로로 쓰시면 됩니다.)

유니티에서 루아 바인딩이 어떻게 이루어지는 지는 잘 모르겠는데, 만약 "시작 파일"의 개념이 없다면(이런 경우가 왕왕 있습니다) 카일루아 전용으로만 쓰이는 시작 파일을 만들어서 거기에서 필요한 파일을 `require`한 뒤 그 파일을 `start_path`로 지정하면 됩니다. 만약 그러한 경우가 많다면 엔진 별로 기본 설정을 마련하는 걸 생각해 보겠습니다.

**Comment by JamesKim2998** [comment]
@lifthrasiir 아하. 감사합니다ㅎㅎ
.kailua_bootstrap.lua (유니티에서 ignore 취급)에서 모든 lua파일을 require하도록 구성해야겠네요.
모든 *.lua.txt 파일을 require하는 식으로
