### ISSUE TITLE
커스텀 타입을 어떻게 리턴 혹은 인자로 받나요?

### ISSUE THREAD

**Issue by JamesKim2998** [devcat-studio/kailua#3]
안녕하세요,
복잡한 객체를 인자로 받거나 리턴값으로 주는 함수의 signature를 어떻게 선언할 수 있나요?

``` lua
Renderer = {
    get_shader = function() --v function() --> Shader    <<<<< 에러: Shader 타입없음
    end,
}

GameObject = {
    get_renderer = function () --v function() --> Renderer     <<<<< 에러: Renderer 타입없음
    end,
}
```

``--# type``을 사용하면 간단한 타입(예를 들어 Vector3)들은 쉽게 표현되는데,
내부에 메소드들이 있는 복잡한 객체는 표현을 어떻게 해야할지 모르겠네요..ㅠㅠ

**Comment by JamesKim2998** [comment]
아래 파일을 참고해서 해결하였습니다.
https://github.com/devcat-studio/kailua/blob/master/kailua_check/src/defs/lua51_io.lua

**Comment by lifthrasiir** [comment]
@JamesKim2998 `--v`의 위치가 틀렸습니다;;; 다음과 같이 쓰셔야 합니다.

```lua
Renderer = {
    get_shader = function() --> Shader
        -- ...
    end
}

-- 또는

GameObject = {
    get_renderer =
        --v function() --> Renderer
        function ()
        end,
}
```

후자는 좀 보기 어려운데요, 문법적으로 애매한 구석이 많아서 현재는 이런 상태입니다. `--^`를 고려해 본 적도 한 번 있습니다. 이런 경우가 많이 있다면 알려 주시면 문법 추가를 고려해 보겠습니다.
