### ISSUE TITLE
객체지향적으로 작성된 예제 코드가 너무나도 간절합니다 8ㅅ8

### ISSUE THREAD

**Issue by JamesKim2998** [devcat-studio/kailua#4]
안녕하세요,

tencent의 xlua로 UnityEngine binding을 하고
kailua로 static type checking을 하려고 시도 중 입니다.

하면서 어떻게 어떻게 될 것 같은 느낌은 드는데,
현재 주어진 문법으로 복잡한 클래스의 타입 정의를 어떻게 해야할지 
벽을 많이 느끼고 있습니다...
그래서 혹시 객체지향적으로 만들어진 예제를 올려주실 수 있을까요?...

그리고 멤버메소드에서 타입이 아직 다 정의되기 전에 사용하는 경우,
아직 구현이 덜 된것 같은데 마일스톤에 포함되어있나요...?
(여기에 https://github.com/devcat-studio/kailua/blob/master/kailua_check/src/defs/lua51_io.lua 아래와 같이 주석이 남겨져 있어서 문의드립니다.
-- TODO method receivers and recursive types are generally not implemented yet)

여담이지만 훌륭한 언어를 만들어주셔서 너무너무 감사합니다. ㅎㅎ
tencent의 xlua와 kailua를 결합하면 엄청난 생산성을 가진 물건이 나올 것 같습니다.

**Comment by lifthrasiir** [comment]
사실 클래스 시스템이 없는 건 아니고 문서화가 안 되어 있는 건데요, 안 되어 있는 이유는 현재 카일루아 클래스 시스템이 정확히 필요한 용례에 맞춰져 만들어져 있고 다른 용도로 쓰기에는 애매한 상태라서 그렇습니다. 유니티가 어떤 상황인지 제가 몰라서 다음과 같은 사항을 알려 주시면 참고할 수 있을 것 같습니다.

* 유저 클래스는 어떻게 생성되나요? 생성이 불가능한가요? 생성시 기존 클래스들과는 어떻게 상호작용하나요? 최상위 클래스가 항상 존재하나요?
* 유저 클래스를 만들 수 있을 경우 생성자는 어떻게 선언하나요? 생성자가 아무 값이나 반환할 수 있나요? 반환된 값이 어디에 쓰이나요?
* 다중 상속이 존재하나요?
* 유저가 어느 시점에서 클래스에 메소드를 추가할 수 있나요?
* (특히 유저 클래스가 만들어질 수 있을 경우) 충돌나는 메소드가 있을 때 어떻게 되나요? 해당 이름으로 선언된 (클래스 상속에서) 가장 최하단의 메소드만 실행되나요? 해당 이름의 모든 메소드가 실행되나요? 후자의 경우 순서는 어느 방향인가요? 유저가 선언한 메소드에서 상위 메소드를 호출하고자 할 경우 어떻게 해야 하나요?

현재 상태는 상속 관련된 문제를 덜 확인해서 외부에 상속이 노출되지 않은 상태입니다. 언급하신 타입이 완전히 선언되지 않았을 경우를 포함해서 현재 동작하는 예제를 일단 만들어 보았습니다. 도움이 되실지 모르겠네요.

```lua
-- 클래스를 만들어 주는 함수
--# assume `class`: [make_class] function() --> any

-- 클래스를 선언
GlobalClass = class() --: module -- module은 후술
local LocalClass = class()

-- 생성자는 `init`으로 가정하며, 항상 처음으로 선언되는 메소드여야 함
--v method(x: integer)
function GlobalClass:init(x)
    self.x = x
    self.y = x * x --: number -- 이 시점에서 변수 선언도 가능함
end

-- `GlobalClass`, `LocalClass` 같은 이름은 클래스 선언 시점부터 타입명으로 간주함
-- (선언이 전역이면 전역 타입, 지역이면 지역 타입으로 간주)
--v method(parent: GlobalClass)
function LocalClass:init(parent)
    self.parent = parent
end

--v method()
function GlobalClass:foo()
    -- 클래스 선언시 쓴 `module`은 해당 클래스에 메소드가 추가될 때 타입 체크를 지연하게 함.
    -- 따라서 아래 메소드는 `bar` 선언 이전이지만 타입 체크가 나중에 일어나서 성공하게 됨.
    -- (타입 체크는 해당 선언을 포함하는 블록, 이 경우 파일 끝에서 일어남.)
    self:bar()
end

--v method()
function GlobalClass:bar()
end

--v method()
function LocalClass:foo()
    -- `module`로 선언되지 않았을 경우 사용 순서대로 선언되어야 함. 아래는 오류.
    self:bar()
end

--v method()
function LocalClass:bar()
end

-- 클래스는 `new` 메소드로 인스턴스화된다고 가정.
local a = GlobalClass.new(3)
local b = LocalClass.new(a)
a:bar()
```

**Comment by JamesKim2998** [comment]
안녕하세요!
적어주신 예시의 module을 참고해서 깔끔하게 해결하였습니다ㅎㅎ
lazy한 타입체킹이 필요했었는데 module이 정확히 이것을 위한거 였네요.

적어주신 질문에 답을 드리고 싶은데, lua 바인딩 생성이 블랙박스 안에 있어서 쉽질 않네요...
(xlua에서 C# 코드를 기반으로 lua 바인딩을 자동 생성해줍니다...)

실제 사용예는 아래 xlua 예제를 참고하시면 도움이 되지 않을까 싶습니다...
* 원본 C# 코드: [https://github.com/Tencent/xLua/blob/master/Assets/XLua/Examples/09_GenericMethod/Foo.cs](url)
* 바인딩된 lua 스크립트 사용예: [https://github.com/Tencent/xLua/blob/master/Assets/XLua/Examples/09_GenericMethod/GenericMethodExample.cs](url)
* 자동생성된 C# -> lua 바인딩:
    https://gist.github.com/JamesKim2998/32bfc79593ee8c7fca80e9246aabdec9
